// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type KainosUser struct {
	ID        uuid.UUID        `json:"id"`
	ClerkID   string           `json:"clerk_id"`
	FirstName *string          `json:"first_name"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type KainosUserAnalysis struct {
	ID          uuid.UUID        `json:"id"`
	Description *string          `json:"description"`
	S3Url       *string          `json:"s3_url"`
	CustomerID  uuid.UUID        `json:"customer_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type KainosUserWorkflow struct {
	ID         uuid.UUID        `json:"id"`
	WorkflowID uuid.UUID        `json:"workflow_id"`
	CustomerID interface{}      `json:"customer_id"`
	MetaData   []byte           `json:"meta_data"`
	CronTime   *string          `json:"cron_time"`
	Status     *string          `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type KainosWorkflow struct {
	ID                  uuid.UUID        `json:"id"`
	WorkflowName        string           `json:"workflow_name"`
	WorkflowDescription string           `json:"workflow_description"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	DeletedAt           pgtype.Timestamp `json:"deleted_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	Price               *float64         `json:"price"`
}

type SystemDefinedAnalysis struct {
	ID           uuid.UUID `json:"id"`
	AnalysisType *string   `json:"analysis_type"`
	Description  *string   `json:"description"`
}
