// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUser struct {
	ID        interface{}      `json:"id"`
	ClerkID   string           `json:"clerk_id"`
	Createdat pgtype.Timestamp `json:"createdat"`
}

type WorkflowsSchedule struct {
	ID           uuid.UUID        `json:"id"`
	RelatedTo    *string          `json:"related_to"`
	WorkflowType string           `json:"workflow_type"`
	ScheduleID   string           `json:"schedule_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
