// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateSystemAnalysis(ctx context.Context, arg CreateSystemAnalysisParams) (SystemDefinedAnalysis, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (KainosUser, error)
	CreateUserAnalysis(ctx context.Context, arg CreateUserAnalysisParams) (KainosUserAnalysis, error)
	CreateUserWorkflow(ctx context.Context, arg CreateUserWorkflowParams) (KainosUserWorkflow, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (KainosWorkflow, error)
	GetUserWorkflow(ctx context.Context) ([]GetUserWorkflowRow, error)
	GetWorkflow(ctx context.Context) ([]KainosWorkflow, error)
}

var _ Querier = (*Queries)(nil)
