// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
)

const createAppUser = `-- name: CreateAppUser :one
INSERT  INTO app_users (clerk_id) VALUES  (clerk_id) RETURNING  id, clerk_id, createdat
`

func (q *Queries) CreateAppUser(ctx context.Context) (AppUser, error) {
	row := q.db.QueryRow(ctx, createAppUser)
	var i AppUser
	err := row.Scan(&i.ID, &i.ClerkID, &i.Createdat)
	return i, err
}
