// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO kainos_user (id, clerk_id, first_name, email) VALUES ($1, $2, $3, $4) returning id, clerk_id, first_name, email, created_at, deleted_at, updated_at
`

type CreateUserParams struct {
	ID        uuid.UUID `json:"id"`
	ClerkID   string    `json:"clerk_id"`
	FirstName *string   `json:"first_name"`
	Email     string    `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (KainosUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.ClerkID,
		arg.FirstName,
		arg.Email,
	)
	var i KainosUser
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FirstName,
		&i.Email,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_id, first_name, email, created_at, deleted_at, updated_at FROM kainos_user
WHERE clerk_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkID string) (KainosUser, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkID)
	var i KainosUser
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FirstName,
		&i.Email,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, clerk_id, first_name, email, created_at, deleted_at, updated_at FROM kainos_user
WHERE id = $1 AND deleted_at is NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (KainosUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i KainosUser
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FirstName,
		&i.Email,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUserByClerkID = `-- name: SoftDeleteUserByClerkID :one
UPDATE kainos_user
SET deleted_at = NOW()
WHERE clerk_id = $1 AND deleted_at is NULL
returning id, clerk_id, first_name, email, created_at, deleted_at, updated_at
`

func (q *Queries) SoftDeleteUserByClerkID(ctx context.Context, clerkID string) (KainosUser, error) {
	row := q.db.QueryRow(ctx, softDeleteUserByClerkID, clerkID)
	var i KainosUser
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FirstName,
		&i.Email,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserByClerkID = `-- name: UpdateUserByClerkID :one
UPDATE kainos_user
SET first_name = $1, email = $2, updated_at = NOW()
WHERE clerk_id = $3 AND deleted_at is NULL
returning id, clerk_id, first_name, email, created_at, deleted_at, updated_at
`

type UpdateUserByClerkIDParams struct {
	FirstName *string `json:"first_name"`
	Email     string  `json:"email"`
	ClerkID   string  `json:"clerk_id"`
}

func (q *Queries) UpdateUserByClerkID(ctx context.Context, arg UpdateUserByClerkIDParams) (KainosUser, error) {
	row := q.db.QueryRow(ctx, updateUserByClerkID, arg.FirstName, arg.Email, arg.ClerkID)
	var i KainosUser
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FirstName,
		&i.Email,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
